/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AttackInterface extends Interface {
  getFunction(
    nameOrSignature: "dummyAccountCount" | "naiveBank" | "openDummyAccounts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "dummyAccountCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "naiveBank", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openDummyAccounts",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "dummyAccountCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "naiveBank", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDummyAccounts",
    data: BytesLike
  ): Result;
}

export interface Attack extends BaseContract {
  connect(runner?: ContractRunner | null): Attack;
  waitForDeployment(): Promise<this>;

  interface: AttackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dummyAccountCount: TypedContractMethod<[], [bigint], "view">;

  naiveBank: TypedContractMethod<[], [string], "view">;

  openDummyAccounts: TypedContractMethod<
    [_noAccounts: BigNumberish],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dummyAccountCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "naiveBank"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "openDummyAccounts"
  ): TypedContractMethod<[_noAccounts: BigNumberish], [void], "payable">;

  filters: {};
}
