/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INaiveBank,
  INaiveBankInterface,
} from "../../Attack.sol/INaiveBank";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "depositFor",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class INaiveBank__factory {
  static readonly abi = _abi;
  static createInterface(): INaiveBankInterface {
    return new Interface(_abi) as INaiveBankInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INaiveBank {
    return new Contract(address, _abi, runner) as unknown as INaiveBank;
  }
}
