/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMoonVault,
  IMoonVaultInterface,
} from "../../Attack.sol/IMoonVault";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "getUserBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMoonVault__factory {
  static readonly abi = _abi;
  static createInterface(): IMoonVaultInterface {
    return new Interface(_abi) as IMoonVaultInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMoonVault {
    return new Contract(address, _abi, runner) as unknown as IMoonVault;
  }
}
